# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  #- MediumFollowersCountPlugin:
  #    username: zhgchgli
  # Automatically fetch Github repo star count
  #- GithubRepoStarsCountPlugin:
  #    - ZhgChgLi/ZMarkupParser
  #    - ZhgChgLi/ZReviewTender
  #    - ZhgChgLi/ZMediumToMarkdown
  #    - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id: G-W5Z6B16L3C

# HTML Title
title: "josephbauser.net"

# Avatar image path
avatar: "images/pixeltar-semitransparent.png"

# Name section text
name: "@coderjoe"

# Tagline section text
tagline: >-
    A software engineer and opensource software advocate from NY who also enjoys larping as a sys-admin, hiking, and biking.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-github"
      text: "github.com/coderjoe"
      url: "https://github.com/coderjoe"
      alt: ""
      rel: ""
      title: "github.com/coderjoe"
      target: "_blank"
  - link:
      icon: "fa-brands fa-mastodon"
      text: "Mastodon - hackyderm.io/@coderjoe"
      url: "https://hachyderm.io/@coderjoe"
      alt: ""
      rel: "me"
      title: "Mastodon - hackyderm.io/@coderjoe"
      target: "_blank"
  # - link:
  #     icon: "fa-brands fa-bluesky"
  #     text: "Bluesky - @coderjoe"
  #     url: "https://bsky.app/profile/coderjoe.net"
  #     alt: ""
  #     title: "Bluesky - @coderjoe"
  #     target: "_blank"
  - link:
      icon: "fa-solid fa-link"
      text: "Blog - coderjoe.net"
      url: "https://coderjoe.net"
      alt: ""
      rel: ""
      title: "Blog - coderjoe.net"
      target: "_blank"
  
# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/josephbauser/"
      title: "Joseph Bauser's LinkedIn"
      alt: "Joseph Bauser's LinkedIn"
      rel: ""
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:contact-joe@via-email.josephbauser.net"
      title: "Email: contact-joe@via-email.josephbauser.net"
      alt: "contact-joe@via-email.josephbauser.net"
      rel: ""
      target: "_blank"

# Footer text
footer: >
    Follow me on GitHub, friend me on Mastodon, or stay connected on LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2025  <a href="https://josephbauser.net" target="_blank">Joseph Bauser</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
